In [1]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/dim_tempo_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 232
Colunas: 7
  data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0      2015-04-18  2015    4          2   Saturday  2015-04       197
1      2017-09-20  2017    9          3  Wednesday  2017-09       144
2      2017-09-21  2017    9          3   Thursday  2017-09       145
3      2017-09-27  2017    9          3  Wednesday  2017-09       146
4      2020-04-14  2020    4          2    Tuesday  2020-04       209
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  232 non-null    datetime64[ns]
 1   ano              232 non-null    int32
 2   mes              232 non-null    int32
 3   trimestre        232 non-null    int32
 4   dia_semana       232 non-null    object
 5   ano_mes          232 non-null    object
 6   tempo_id         232 non-null    int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 10.1+ KB
None

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  232 non-null    datetime64[ns]
 1   ano              232 non-null    int32
 2   mes              232 non-null    int32
 3   trimestre        232 non-null    int32
 4   dia_semana       232 non-null    object
 5   ano_mes          232 non-null    object
 6   tempo_id         232 non-null    int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 10.1+ KB

In [3]:
df.isnull().sum()

data_referencia    0
ano                0
mes                0
trimestre          0
dia_semana         0
ano_mes            0
tempo_id           0
dtype: int64

In [4]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/dim_hospital_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 522
Colunas: 17
  id_hospital codigo_municipio nome_municipio_hospital  latitude_hospital  \
0     0013102           410020            Adrianópolis           -24.6606
1     0013129           410030           Agudos do Sul           -25.9899
2     0013633           410400   Campina Grande do Sul           -25.3044
3     0013838           410420             Campo Largo           -25.4525
4     0013846           410420             Campo Largo           -25.4525

   longitude_hospital  leitos_totais  leitos_contratados  leitos_sus  \
0            -48.9922              3                   0           3
1            -49.3343             12                   0          12
2            -49.0551            483                   0         411
3            -49.5290            156                   0         145
4            -49.5290            884                   0         838

   leitos_nao_sus esfera tipo_unidade nivel_hierarquico natureza_juridica  \
0               0                  15                                1244
1               0                  73                                1244
2              72                  05                                3999
3              11                  05                                2062
4              46                  05                                2054

  porte_hospitalar         alta_complexidade esfera_classificacao  \
0      Micro Porte  Baixa/Media Complexidade        Não Informado
1      Micro Porte  Baixa/Media Complexidade        Não Informado
2     Grande Porte  Baixa/Media Complexidade        Não Informado
3     Grande Porte  Baixa/Media Complexidade        Não Informado
4     Grande Porte  Baixa/Media Complexidade        Não Informado

   percentual_sus
0          100.00
1          100.00
2           85.09
3           92.95
4           94.80
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_hospital              522 non-null    object
 1   codigo_municipio         522 non-null    object
 2   nome_municipio_hospital  522 non-null    object
 3   latitude_hospital        522 non-null    float64
 4   longitude_hospital       522 non-null    float64
 5   leitos_totais            522 non-null    int64
 6   leitos_contratados       522 non-null    int64
 7   leitos_sus               522 non-null    int64
 8   leitos_nao_sus           522 non-null    int64
 9   esfera                   522 non-null    object
 10  tipo_unidade             522 non-null    object
 11  nivel_hierarquico        522 non-null    object
 12  natureza_juridica        522 non-null    object
 13  porte_hospitalar         522 non-null    object
 14  alta_complexidade        522 non-null    object
 15  esfera_classificacao     522 non-null    object
 16  percentual_sus           522 non-null    float64
dtypes: float64(3), int64(4), object(10)
memory usage: 69.5+ KB
None

In [7]:
df.isnull().sum()

id_hospital                0
codigo_municipio           0
nome_municipio_hospital    0
latitude_hospital          0
longitude_hospital         0
leitos_totais              0
leitos_contratados         0
leitos_sus                 0
leitos_nao_sus             0
esfera                     0
tipo_unidade               0
nivel_hierarquico          0
natureza_juridica          0
porte_hospitalar           0
alta_complexidade          0
esfera_classificacao       0
percentual_sus             0
dtype: int64

In [8]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/dim_municipio_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 399
Colunas: 4
  codigo_municipio       nome_municipio  latitude  longitude
0           410010               Abatiá  -23.3049   -50.3133
1           410020         Adrianópolis  -24.6606   -48.9922
2           410030        Agudos do Sul  -25.9899   -49.3343
3           410040  Almirante Tamandaré  -25.3188   -49.3037
4           410045   Altamira do Paraná  -24.7983   -52.7128
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   codigo_municipio  399 non-null    object
 1   nome_municipio    399 non-null    object
 2   latitude          399 non-null    float64
 3   longitude         399 non-null    float64
dtypes: float64(2), object(2)
memory usage: 12.6+ KB
None

In [9]:
df.isnull().sum()

codigo_municipio    0
nome_municipio      0
latitude            0
longitude           0
dtype: int64

In [10]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/fato_internacao_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 532,538
Colunas: 21
   internacao_id id_hospital codigo_municipio_paciente  tempo_id  \
0              1     2781700                    410050         1
1              2     2781700                    410050         1
2              3     2781700                    410050         1
3              4     2781700                    410050         1
4              5     2781700                    410050         2

  codigo_diagnostico data_internacao data_saida  valor_procedimento  \
0               K359      2023-11-23 2023-11-24               99.73
1               K359      2023-11-23 2023-11-24               48.00
2               K359      2023-11-23 2023-11-24               13.30
3               K359      2023-11-23 2023-11-24                0.00
4               K359      2023-11-27 2023-11-29               89.23

   dias_internacao  paciente_viajou  ... latitude_paciente  \
0                1            False  ...          -23.8759
1                1            False  ...          -23.8759
2                1            False  ...          -23.8759
3                1            False  ...          -23.8759
4                2            False  ...          -23.8759

   longitude_paciente  nome_municipio_hospital latitude_hospital  \
0            -53.8958                  Altônia          -23.8759
1            -53.8958                  Altônia          -23.8759
2            -53.8958                  Altônia          -23.8759
3            -53.8958                  Altônia          -23.8759
4            -53.8958                  Altônia          -23.8759

   longitude_hospital  distancia_estimada_km  ano_competencia  \
0            -53.8958                    0.0             2024
1            -53.8958                    0.0             2024
2            -53.8958                    0.0             2024
3            -53.8958                    0.0             2024
4            -53.8958                    0.0             2024

   mes_competencia  dia_semana  tipo_dia
0                1    Thursday  Dia Util
1                1    Thursday  Dia Util
2                1    Thursday  Dia Util
3                1    Thursday  Dia Util
4                1      Monday  Dia Util

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532538 entries, 0 to 532537
Data columns (total 21 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   internacao_id              532538 non-null  int64
 1   id_hospital                532538 non-null  object
 2   codigo_municipio_paciente  532538 non-null  object
 3   tempo_id                   532538 non-null  int64
 4   codigo_diagnostico         532538 non-null  object
 5   data_internacao            532538 non-null  datetime64[ns]
 6   data_saida                 532538 non-null  datetime64[ns]
 7   valor_procedimento         532538 non-null  float64
 8   dias_internacao            532538 non-null  int64
 9   paciente_viajou            532538 non-null  bool
 10  nome_municipio_paciente    532538 non-null  object
 11  latitude_paciente          532538 non-null  float64
 12  longitude_paciente         532538 non-null  float64
 13  nome_municipio_hospital    532538 non-null  object
 14  latitude_hospital          532538 non-null  float64
 15  longitude_hospital         532538 non-null  float64
 16  distancia_estimada_km      532538 non-null  float64
 17  ano_competencia            532538 non-null  int64
 18  mes_competencia            532538 non-null  int64
 19  dia_semana                 532538 non-null  object
 20  tipo_dia                   532538 non-null  object
dtypes: bool(1), datetime64[ns](2), float64(6), int64(5), object(7)
memory usage: 81.8+ MB
None

In [11]:
df.isnull().sum()

internacao_id                0
id_hospital                  0
codigo_municipio_paciente    0
tempo_id                     0
codigo_diagnostico           0
data_internacao              0
data_saida                   0
valor_procedimento           0
dias_internacao              0
paciente_viajou              0
nome_municipio_paciente      0
latitude_paciente            0
longitude_paciente           0
nome_municipio_hospital      0
latitude_hospital            0
longitude_hospital           0
distancia_estimada_km        0
ano_competencia              0
mes_competencia              0
dia_semana                   0
tipo_dia                     0
dtype: int64